apiVersion: apps/v1
kind: Deployment
metadata:
  name: cust-deploy
  namespace: praveen-ns
  labels:
    app: cust-dep
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  selector:
    matchLabels:
      app: fitness
  replicas: 8
  template:
    metadata:
      labels:
        app: fitness
    spec:
      containers:
        - name: fitness-container
          image: muralisocial123/fitness-app:v1.0.1
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: cust-deploy-svc 
  namespace: praveen-ns
spec:
  selector:
    app: fitness
  ports:
    - port: 3001 #host portnumber || service port number used to expose application to internet
      targetPort: 5000 #target port || application port || contaier port
      protocol: TCP
  type: ClusterIP 