apiVersion: apps/v1
kind: Deployment
metadata:
  name: ey-deployment
  namespace: praveen-ns
  labels:
    app: dep 
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate: 
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: ey-dep
  template:
    metadata: 
      labels:
        app: ey-dep
    spec:
      containers:
        - name: ey-dep-container
          image: praveenx03/retail:v1.1.0
          ports:
            - containerPort: 80
